<?php
// autogenerated froxlor file

$sql = [
	'debug' => false,
	'host' => 'localhost',
	'user' => 'froxlor',
	'password' => <<<'EOT'
Game23_23!
EOT,
	'db' => 'froxlor',
];
$sql_root = [
	'0' => [
		'caption' => 'Default',
		'host' => 'localhost',
		'user' => 'froxroot',
		'password' => <<<'EOT'
MapleR0ll23!
EOT,
	],
];
